$src = "C:\Users\nisha\.gemini\antigravity\brain\b213351a-158b-4b84-9c93-09075405f107"
$dest = "c:\Users\nisha\OneDrive\Desktop\projects\gsp\src\assets\images"

New-Item -ItemType Directory -Force -Path "$dest\hero"
New-Item -ItemType Directory -Force -Path "$dest\services"
New-Item -ItemType Directory -Force -Path "$dest\projects"
New-Item -ItemType Directory -Force -Path "$dest\equipment"
New-Item -ItemType Directory -Force -Path "$dest\about"
New-Item -ItemType Directory -Force -Path "$dest\gallery"

Get-ChildItem -Path $src -Filter "hero_asphalt_*.jpg" | Copy-Item -Destination "$dest\hero\hero_asphalt.jpg"
Get-ChildItem -Path $src -Filter "service_paving_*.jpg" | Copy-Item -Destination "$dest\services\service_paving.jpg"
Get-ChildItem -Path $src -Filter "service_construction_*.jpg" | Copy-Item -Destination "$dest\services\service_construction.jpg"
Get-ChildItem -Path $src -Filter "service_infra_*.jpg" | Copy-Item -Destination "$dest\services\service_infra.jpg"
Get-ChildItem -Path $src -Filter "project_highway_*.jpg" | Copy-Item -Destination "$dest\projects\project_highway.jpg"
Get-ChildItem -Path $src -Filter "project_downtown_*.jpg" | Copy-Item -Destination "$dest\projects\project_downtown.jpg"
Get-ChildItem -Path $src -Filter "eq_paver_*.jpg" | Copy-Item -Destination "$dest\equipment\eq_paver.jpg"
Get-ChildItem -Path $src -Filter "eq_roller_*.jpg" | Copy-Item -Destination "$dest\equipment\eq_roller.jpg"
Get-ChildItem -Path $src -Filter "about_team_*.jpg" | Copy-Item -Destination "$dest\about\about_team.jpg"
Get-ChildItem -Path $src -Filter "cta_bg_*.jpg" | Copy-Item -Destination "$dest\hero\cta_bg.jpg"
